# Generated by Django 5.2.8 on 2025-11-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Office'), ('AIRPORT', 'Airport')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SEALED', 'Sealed'), ('IN_MANIFEST', 'In Manifest'), ('DISPATCHED', 'Dispatched')], default='OPEN', max_length=20)),
                ('total_parcels', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sealed_bags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('customer_type', models.CharField(choices=[('REGULAR', 'Regular'), ('CREDIT', 'Credit Account')], default='REGULAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('mawb_number', models.CharField(blank=True, help_text='Master AWB from airline', max_length=50, null=True)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('total_bags', models.IntegerField(default=0)),
                ('total_parcels', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('DEPARTED', 'Departed from Bangladesh'), ('ARRIVED', 'Arrived in Hong Kong')], default='DRAFT', max_length=20)),
                ('airline_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('bags', models.ManyToManyField(related_name='manifests', to='exportimport.bag')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manifests', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_manifests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-departure_date', '-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('external_awb', models.CharField(blank=True, help_text='External AWB (from HK/Airline)', max_length=50, null=True)),
                ('direction', models.CharField(choices=[('BD_TO_HK', 'Bangladesh to Hong Kong'), ('HK_TO_BD', 'Hong Kong to Bangladesh')], max_length=20)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.TextField()),
                ('sender_country', models.CharField(default='Bangladesh', max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('recipient_country', models.CharField(default='Hong Kong', max_length=100)),
                ('contents', models.TextField(help_text='Parcel contents')),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declared_currency', models.CharField(choices=[('USD', 'US Dollar'), ('HKD', 'Hong Kong Dollar'), ('BDT', 'Taka')], default='USD', max_length=3)),
                ('weight_estimated', models.DecimalField(decimal_places=2, help_text='KG', max_digits=6)),
                ('weight_actual', models.DecimalField(blank=True, decimal_places=2, help_text='KG', max_digits=6, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='CM', max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='CM', max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='CM', max_digits=6, null=True)),
                ('service_type', models.CharField(choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard')], default='EXPRESS', max_length=20)),
                ('current_status', models.CharField(choices=[('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_HK', 'In Transit to Hong Kong'), ('ARRIVED_AT_HK', 'Arrived at Hong Kong'), ('DELIVERED_IN_HK', 'Delivered in Hong Kong'), ('BOOKED', 'Booked'), ('IN_TRANSIT_TO_BD', 'In Transit to Bangladesh'), ('ARRIVED_AT_BD', 'Arrived at Bangladesh'), ('CUSTOMS_CLEARANCE_BD', 'Customs Clearance Bangladesh'), ('CUSTOMS_CLEARED_BD', 'Customs Cleared Bangladesh'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION_DAMAGED', 'Exception - Damaged'), ('EXCEPTION_CUSTOMS_HOLD', 'Exception - Customs Hold'), ('RETURN_TO_SENDER', 'Return to Sender')], default='BOOKED', max_length=50)),
                ('payment_method', models.CharField(choices=[('PREPAID', 'Prepaid'), ('CASH', 'Cash at Warehouse'), ('CREDIT', 'Credit Account'), ('COD', 'Cash on Delivery')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_cod', models.BooleanField(default=False)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_liquid', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('hk_reference', models.CharField(blank=True, help_text='HK warehouse reference', max_length=100, null=True)),
                ('mawb_number', models.CharField(blank=True, help_text='Master AWB', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='exportimport.bag')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='exportimport.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_shipments', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proof', to='exportimport.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('DAMAGED', 'Damaged'), ('CUSTOMS_HOLD', 'Customs Hold'), ('ADDRESS_ISSUE', 'Address Issue'), ('RECIPIENT_UNAVAILABLE', 'Recipient Unavailable'), ('WEIGHT_DISCREPANCY', 'Weight Discrepancy'), ('PROHIBITED_ITEM', 'Prohibited Item'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('resolution_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_exceptions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='exportimport.shipment')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BD_STAFF', 'Bangladesh Operations Staff'), ('BD_MANAGER', 'Bangladesh Manager'), ('HK_STAFF', 'Hong Kong Operations Staff'), ('HK_MANAGER', 'Hong Kong Manager'), ('DRIVER', 'Delivery Driver'), ('ADMIN', 'System Administrator')], max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exportimport.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='exportimport.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
