# Generated by Django 5.2.8 on 2025-11-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
    ]
