# Generated by Django 5.2.8 on 2025-11-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0002_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
    ]
