# Generated by Django 5.2.8 on 2025-11-23 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0003_remove_customer_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='bag',
        ),
        migrations.AddField(
            model_name='bag',
            name='shipments',
            field=models.ManyToManyField(blank=True, help_text='Select shipments for this bag', related_name='bags', to='exportimport.shipment'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='sealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sealed_bags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bag',
            name='total_parcels',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bag',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
