# Generated by Django 5.2.8 on 2025-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0004_remove_shipment_bag_bag_shipments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
    ]
