# Generated by Django 5.2.8 on 2025-11-30 06:06

from django.db import migrations, models
from django.db import connection


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields if they exist"""
    with connection.cursor() as cursor:
        # Check if columns exist before trying to remove them
        cursor.execute("PRAGMA table_info(exportimport_bag)")
        columns = [row[1] for row in cursor.fetchall()]
        
        # Only proceed if old fields exist
        if 'total_parcels' in columns or 'total_weight' in columns:
            # Fields exist, they will be removed by the RemoveField operations
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0006_convert_bag_to_onetoone'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, migrations.RunPython.noop),
        
        # Try to remove fields - will be skipped if they don't exist
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='bag',
                    name='shipments',
                ),
                migrations.RemoveField(
                    model_name='bag',
                    name='total_parcels',
                ),
                migrations.RemoveField(
                    model_name='bag',
                    name='total_weight',
                ),
            ],
            database_operations=[
                # Database operations will be handled manually if needed
            ],
        ),
        
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_HK', 'In Transit to Hong Kong'), ('ARRIVED_AT_HK', 'Arrived at Hong Kong'), ('DELIVERED_IN_HK', 'Delivered in Hong Kong'), ('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('IN_TRANSIT_TO_BD', 'In Transit to Bangladesh'), ('ARRIVED_AT_BD', 'Arrived at Bangladesh'), ('CUSTOMS_CLEARANCE_BD', 'Customs Clearance Bangladesh'), ('CUSTOMS_CLEARED_BD', 'Customs Cleared Bangladesh'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION_DAMAGED', 'Exception - Damaged'), ('EXCEPTION_CUSTOMS_HOLD', 'Exception - Customs Hold'), ('RETURN_TO_SENDER', 'Return to Sender')], default='BOOKED', max_length=50),
        ),
    ]
