# Generated by Django 5.2.8 on 2026-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0008_remove_old_bag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='awb_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_HK', 'In Transit to Hong Kong'), ('ARRIVED_AT_HK', 'Arrived at Hong Kong'), ('DELIVERED_IN_HK', 'Delivered in Hong Kong'), ('EXCEPTION_DAMAGED', 'Exception - Damaged'), ('EXCEPTION_CUSTOMS_HOLD', 'Exception - Customs Hold'), ('RETURN_TO_SENDER', 'Return to Sender')], default='BOOKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='direction',
            field=models.CharField(choices=[('BD_TO_HK', 'Bangladesh to Hong Kong')], max_length=20),
        ),
    ]
