# Generated by Django 5.2.8 on 2026-02-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0009_alter_shipment_awb_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='created_by',
            field=models.ForeignKey(help_text='Staff who created the bag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bag',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Maximum weight limit in KG', max_digits=8),
        ),
        migrations.AddField(
            model_name='bag',
            name='unseal_reason',
            field=models.TextField(blank=True, help_text='Reason for unsealing the bag', null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='unsealed_at',
            field=models.DateTimeField(blank=True, help_text='When the bag was unsealed', null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='unsealed_by',
            field=models.ForeignKey(blank=True, help_text='Staff who unsealed the bag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsealed_bags', to=settings.AUTH_USER_MODEL),
        ),
    ]
