# Generated by Django 5.2.8 on 2026-02-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0010_bag_created_by_bag_max_weight_bag_unseal_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='max_weight',
        ),
    ]
