# Generated by Django 5.2.8 on 2026-02-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0011_remove_bag_max_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(upload_to='air_invoices/')),
                ('page_count', models.IntegerField(help_text='Number of pages in PDF (equals number of parcels)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('bag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='air_invoice', to='exportimport.bag')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Air Invoice',
                'verbose_name_plural': 'Air Invoices',
                'ordering': ['-generated_at'],
            },
        ),
    ]
