# Generated by Django 5.2.8 on 2026-02-18 18:53

from django.db import migrations, models
from django.db import connection


def check_and_create_shipments_table(apps, schema_editor):
    """Check if the shipments ManyToMany table exists, if not create it"""
    with connection.cursor() as cursor:
        # Check if the table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='exportimport_bag_shipments'
        """)
        table_exists = cursor.fetchone() is not None
        
        if not table_exists:
            # Table doesn't exist, it will be created by AddField operation
            pass
        # If table exists, AddField will skip creation


def migrate_onetoone_to_manytomany(apps, schema_editor):
    """Migrate existing OneToOne relationships to ManyToMany"""
    Bag = apps.get_model('exportimport', 'Bag')
    
    # Get all bags that have a shipment in the OneToOne field
    for bag in Bag.objects.filter(shipment__isnull=False):
        # Add the shipment to the ManyToMany field
        bag.shipments.add(bag.shipment)


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0012_airinvoice'),
    ]

    operations = [
        # Run check before adding field
        migrations.RunPython(check_and_create_shipments_table, migrations.RunPython.noop),
        
        # Add the ManyToManyField (will skip if table already exists)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='bag',
                    name='shipments',
                    field=models.ManyToManyField(blank=True, related_name='bags', to='exportimport.shipment'),
                ),
            ],
            database_operations=[
                # Only create table if it doesn't exist
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS exportimport_bag_shipments (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            bag_id INTEGER NOT NULL REFERENCES exportimport_bag(id) ON DELETE CASCADE,
                            shipment_id INTEGER NOT NULL REFERENCES exportimport_shipment(id) ON DELETE CASCADE,
                            UNIQUE(bag_id, shipment_id)
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS exportimport_bag_shipments"
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS exportimport_bag_shipments_bag_id ON exportimport_bag_shipments(bag_id)",
                    reverse_sql="DROP INDEX IF EXISTS exportimport_bag_shipments_bag_id"
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS exportimport_bag_shipments_shipment_id ON exportimport_bag_shipments(shipment_id)",
                    reverse_sql="DROP INDEX IF EXISTS exportimport_bag_shipments_shipment_id"
                ),
            ],
        ),
        
        # Migrate data from OneToOne to ManyToMany
        migrations.RunPython(migrate_onetoone_to_manytomany, migrations.RunPython.noop),
    ]
