# Generated by Django 5.2.8 on 2026-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0013_migrate_bag_shipment_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='shipments',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='shipment',
        ),
        migrations.AddField(
            model_name='bag',
            name='shipment',
            field=models.ManyToManyField(blank=True, related_name='bags', to='exportimport.shipment'),
        ),
    ]
