# Generated by Django 5.2.8 on 2026-02-18 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0014_remove_bag_shipments_remove_bag_shipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Generated PDF export', upload_to='manifest_exports/pdf/')),
                ('excel_file', models.FileField(help_text='Generated Excel export', upload_to='manifest_exports/excel/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manifest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export', to='exportimport.manifest')),
            ],
            options={
                'verbose_name': 'Manifest Export',
                'verbose_name_plural': 'Manifest Exports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
