# Generated by Django 5.2.8 on 2026-02-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0015_manifestexport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='sender_address',
            new_name='shipper_address',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='sender_country',
            new_name='shipper_country',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='sender_name',
            new_name='shipper_name',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='sender_phone',
            new_name='shipper_phone',
        ),
    ]
