# Generated by Django 5.2.8 on 2026-02-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0016_rename_sender_address_shipment_shipper_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='invoice',
            field=models.FileField(blank=True, help_text='Commercial invoice document (PDF or image)', null=True, upload_to='invoices/%Y/%m/'),
        ),
    ]
