# Generated by Django 5.2.8 on 2026-02-24 05:51

import exportimport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0017_shipment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='shipments',
            field=models.ManyToManyField(blank=True, help_text='Individual shipments not in bags', related_name='manifests', to='exportimport.shipment'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='bags',
            field=models.ManyToManyField(blank=True, related_name='manifests', to='exportimport.bag'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice',
            field=models.FileField(blank=True, help_text='Commercial invoice document (PDF or image)', null=True, upload_to=exportimport.models.invoice_upload_path),
        ),
        migrations.DeleteModel(
            name='AirInvoice',
        ),
    ]
