# Generated by Django 5.2.8 on 2026-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0018_add_shipments_to_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items in shipment'),
        ),
    ]
