# Generated by Django 5.2.8 on 2026-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0019_shipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='contents',
            field=models.TextField(blank=True, help_text='Parcel contents', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='declared_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('CASH', 'Cash at Warehouse'), ('CREDIT', 'Credit Account'), ('COD', 'Cash on Delivery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard')], default='EXPRESS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_estimated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='KG', max_digits=6, null=True),
        ),
    ]
