# Generated by Django 5.2.8 on 2026-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0020_alter_shipment_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Number of items in shipment', null=True),
        ),
    ]
