# Generated by Django 5.2.8 on 2026-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0021_alter_shipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_HK', 'In Transit to Hong Kong'), ('ARRIVED_AT_HK', 'Arrived at Hong Kong'), ('DELIVERED_IN_HK', 'Delivered in Hong Kong'), ('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_UK', 'In Transit to United Kingdom'), ('ARRIVED_AT_UK', 'Arrived at United Kingdom'), ('DELIVERED_IN_UK', 'Delivered in United Kingdom'), ('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_CN', 'In Transit to China'), ('ARRIVED_AT_CN', 'Arrived at China'), ('DELIVERED_IN_CN', 'Delivered in China'), ('EXCEPTION_DAMAGED', 'Exception - Damaged'), ('EXCEPTION_CUSTOMS_HOLD', 'Exception - Customs Hold'), ('RETURN_TO_SENDER', 'Return to Sender')], default='BOOKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='direction',
            field=models.CharField(choices=[('BD_TO_HK', 'Bangladesh to Hong Kong'), ('BD_TO_UK', 'Bangladesh to United Kingdom'), ('BD_TO_CN', 'Bangladesh to China')], max_length=20),
        ),
    ]
