# Generated by Django 5.2.8 on 2026-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0022_alter_shipment_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='direction',
            field=models.CharField(blank=True, choices=[('BD_TO_HK', 'Bangladesh to Hong Kong'), ('BD_TO_UK', 'Bangladesh to United Kingdom'), ('BD_TO_CN', 'Bangladesh to China')], max_length=20, null=True),
        ),
    ]
