# Generated by Django 5.2.8 on 2026-02-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0023_alter_shipment_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, help_text='Shipment date (editable)', null=True),
        ),
    ]
